### ISSUE TITLE
Upgrade Pydantic to v2

### ISSUE THREAD

**Issue by vedem1192** [IBM/ibm-generative-ai#67]
**Context**

Most updated version of Pydantic is v2. There needs to be some changes to the code for accommodate for the new version, which currently throws errors.

**Alternatives**

No

**Has the feature been requested before?**

No

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by vedem1192** [comment]
https://docs.pydantic.dev/2.0/migration/

**Comment by jpwsutton** [comment]
I've got PR #115 in draft state, but as langchain does not support pydantic v2 we will either have to wait until it does, or drop support for langchain in newer versions of ibm-generative-ai until it does.

**Comment by agiova** [comment]
Hi @jpwsutton, would it make sense to re-run the builds that were failing because of langchain not compatible with pydantic v2? (adding a lower bound to langchain, if it works, would be great) 
Now it seems at least partially addressed.
https://github.com/langchain-ai/langchain/issues/8984#issuecomment-1682991691

**Comment by assaftibm** [comment]
Hi, any idea when this will be implemented? (I saw the PR and left a comment there too)
My issue is that pydantic 2 cannot be used in new projects as long as gen-ai requires pydenatic 1.x

**Comment by Tomas2D** [comment]
@assaftibm will be fixed in an upcoming release
